# Generated by Django 5.0.1 on 2025-01-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_car_lead_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.car'),
        ),
    ]
